resource "local_file" "pet" {
  filename = var.filename
  #content         = var.content
  content         = "My favorite pet is ${random_pet.randomize-pets.id}"
  file_permission = var.file_permission
}

resource "random_pet" "randomize-pets" {
  prefix    = var.prefix
  separator = var.separator
  length    = var.length
}

resource "local_file" "my-pet" {
  filename        = "/home/brayanmarin/animals.txt"
  content         = var.file_content["dog"]
  file_permission = "0700"
}

output "pet-name" {
  value       = random_pet.randomize-pets.id
  description = "record the value of the pet ID generated by the random_pet resource"
}

resource "local_file" "dog" {
  filename        = "/home/brayanmarin/dog.txt"
  content         = "I have a dog"
  file_permission = "0700"
}

resource "local_file" "cat" {
  filename        = "/home/brayanmarin/cat.txt"
  content         = "I have a cat"
  file_permission = "0700"
}
